# Generated by Django 4.1.4 on 2023-01-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0002_tag_post_source_link_review_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
