# Generated by Django 4.1.3 on 2023-02-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0005_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='static/images'),
        ),
    ]
