# Generated by Django 4.1.3 on 2023-02-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0008_alter_post_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, default='static/images/default.jpg', null=True, upload_to=''),
        ),
    ]
