# Generated by Django 4.1.3 on 2023-02-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0009_alter_post_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
    ]
