# Generated by Django 4.1.3 on 2023-03-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_profile_id'),
        ('dev', '0013_review_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
